// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for DeleteOldLambdaLayerVersionsFunction
 */
export interface DeleteOldLambdaLayerVersionsFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambda/delete-old-lambda-layer-versions.
 */
export class DeleteOldLambdaLayerVersionsFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DeleteOldLambdaLayerVersionsFunctionProps) {
    super(scope, id, {
      description: 'src/lambda/delete-old-lambda-layer-versions.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/lambda/delete-old-lambda-layer-versions.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}